# Generated by Django 4.2.13 on 2024-07-08 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_name',
            field=models.CharField(max_length=255, unique=True, verbose_name='category name'),
        ),
    ]
