# Generated by Django 4.2.13 on 2024-07-12 19:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_product_created_at_product_slug_alter_stock_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='name in URL'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='size',
            field=models.CharField(choices=[('X-Small', 'XS'), ('Small', 'S'), ('Medium', 'M'), ('Large', 'L'), ('X-Large', 'XL')], max_length=20),
        ),
    ]
