# Generated by Django 4.2.13 on 2024-07-14 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_product_created_at_alter_product_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['product']},
        ),
    ]
