# Generated by Django 4.2.13 on 2024-07-14 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_stock_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='fit',
            field=models.CharField(choices=[('regular_fit', 'Regular Fit'), ('relaxed_fit', 'Relaxed Fit'), ('slim_fit', 'Slim Fit')], default='regular_fit', max_length=255),
        ),
    ]
