# Generated by Django 4.2.13 on 2024-07-14 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_product_active_alter_product_fit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='fit',
            field=models.CharField(choices=[('Regular Fit', 'regular_fit'), ('Relaxed Fit', 'relaxed_fit'), ('Slim Fit', 'slim_fit')], default='regular_fit', max_length=255),
        ),
    ]
