# Generated by Django 4.2.13 on 2024-07-17 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_bagitem_bag_bagitem_product_bagitem_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bagitem',
            name='size',
            field=models.CharField(choices=[('X-Small', 'XS'), ('Small', 'S'), ('Medium', 'M'), ('Large', 'L'), ('X-Large', 'XL')], max_length=20, null=True),
        ),
    ]
