# Generated by Django 4.2.13 on 2024-07-24 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_bagitem_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ShippingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_email', models.EmailField(max_length=255)),
                ('customer_number', models.CharField(max_length=255)),
                ('governorate', models.CharField(choices=[('Cairo', 'CAI'), ('Giza', 'GIZ'), ('Alexandria', 'ALX'), ('North Coast', 'NC')], max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('building_no', models.PositiveSmallIntegerField()),
                ('landmark', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
