# Generated by Django 4.2.13 on 2024-07-30 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_delete_order_bag_order_date_bag_ordered_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bagitem',
            name='bag',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.bag'),
        ),
    ]
