# Generated by Django 4.2.13 on 2024-07-30 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_bagitem_bag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bagitem',
            name='bag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.bag'),
        ),
    ]
