# Generated by Django 4.2.13 on 2024-07-30 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_bag_shipping_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bag',
            name='shipping_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.shippinginfo'),
        ),
    ]
