# Generated by Django 4.2.13 on 2024-07-31 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_bag_shipping_info'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bag',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-active', 'created_at']},
        ),
        migrations.AddField(
            model_name='bag',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
    ]
