# Generated by Django 4.2.13 on 2024-07-31 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_bag_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bag',
            name='shipping_info',
        ),
        migrations.AddField(
            model_name='shippinginfo',
            name='bag',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.bag'),
        ),
    ]
