# Generated by Django 4.2.13 on 2024-07-31 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_bag_shipping_info_shippinginfo_bag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bag',
            options={'ordering': ['delivered', 'order_date'], 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.RemoveField(
            model_name='shippinginfo',
            name='building_no',
        ),
        migrations.RemoveField(
            model_name='shippinginfo',
            name='street',
        ),
        migrations.AddField(
            model_name='shippinginfo',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
