# Generated by Django 4.2.13 on 2024-07-06 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_options_alter_category_cat_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('product', 'size')},
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['product', 'size'], name='products_st_product_39cfcc_idx'),
        ),
    ]
